const CONSTANTS = {
  LOGIN_USER_REQUESTED: 'LOGIN_USER_REQUESTED',
  LOGIN_USER_FAILED: 'LOGIN_USER_FAILED',
  LOGIN_USER_SUCCEEDED: 'LOGIN_USER_SUCCEEDED',

  RESTORE_DATA_REQUESTED: 'RESTORE_DATA_REQUESTED',
  RESTORE_DATA_FAILED: 'RESTORE_DATA_FAILED',
  RESTORE_DATA_SUCCEEDED: 'RESTORE_DATA_SUCCEEDED',

  GET_USER_DETAILS_REQUESTED: 'GET_USER_DETAILS_REQUESTED',
  GET_USER_DETAILS_FAILED: 'GET_USER_DETAILS_FAILED',
  GET_USER_DETAILS_SUCCEEDED: 'GET_USER_DETAILS_SUCCEEDED',

  CHANGE_PASSWORD_REQUESTED: 'CHANGE_PASSWORD_REQUESTED',
  CHANGE_PASSWORD_FAILED: 'CHANGE_PASSWORD_FAILED',
  CHANGE_PASSWORD_SUCCEEDED: 'CHANGE_PASSWORD_SUCCEEDED',

  GET_USER_PROFILE_REQUESTED: 'GET_USER_PROFILE_REQUESTED',
  GET_USER_PROFILE_FAILED: 'GET_USER_PROFILE_FAILED',
  GET_USER_PROFILE_SUCCEEDED: 'GET_USER_PROFILE_SUCCEEDED',

  FORGOT_PASSWORD_REQUESTED: 'FORGOT_PASSWORD_REQUESTED',
  FORGOT_PASSWORD_FAILED: 'FORGOT_PASSWORD_FAILED',
  FORGOT_PASSWORD_SUCCEEDED: 'FORGOT_PASSWORD_SUCCEEDED',

  UPDATE_IMAGE_REQUESTED: 'UPDATE_IMAGE_REQUESTED',
  UPDATE_IMAGE_FAILED: 'UPDATE_IMAGE_FAILED',
  UPDATE_IMAGE_SUCCEEDED: 'UPDATE_IMAGE_SUCCEEDED',

  // KPMG Postes
  GET_POSTES_REQUESTED: 'GET_POSTES_REQUESTED',
  GET_POSTES_FAILED: 'GET_POSTES_FAILED',
  GET_POSTES_SUCCEEDED: 'GET_POSTES_SUCCEEDED',

  GET_LIKES_FOR_POST_REQUESTED: 'GET_LIKES_FOR_POST_REQUESTED',
  GET_LIKES_FOR_POST_FAILED: 'GET_LIKES_FOR_POST_FAILED',
  GET_LIKES_FOR_POST_SUCCEEDED: 'GET_LIKES_FOR_POST_SUCCEEDED',

  LIKE_UNLIKE_FOR_POST_REQUESTED: 'LIKE_UNLIKE_FOR_POST_REQUESTED',
  LIKE_UNLIKE_FOR_POST_FAILED: 'LIKE_UNLIKE_FOR_POST_FAILED',
  LIKE_UNLIKE_FOR_POST_SUCCEEDED: 'LIKE_UNLIKE_FOR_POST_SUCCEEDED',

  GET_COMMENTS_FOR_POST_REQUESTED: 'GET_COMMENTS_FOR_POST_REQUESTED',
  GET_COMMENTS_FOR_POST_FAILED: 'GET_COMMENTS_FOR_POST_FAILED',
  GET_COMMENTS_FOR_POST_SUCCEEDED: 'GET_COMMENTS_FOR_POST_SUCCEEDED',

  CREATE_COMMENT_FOR_POST_REQUESTED: 'CREATE_COMMENT_FOR_POST_REQUESTED',
  CREATE_COMMENT_FOR_POST_FAILED: 'CREATE_COMMENT_FOR_POST_FAILED',
  CREATE_COMMENT_FOR_POST_SUCCEEDED: 'CREATE_COMMENT_FOR_POST_SUCCEEDED',


  DELETE_COMMENT_FOR_POST_REQUESTED: 'DELETE_COMMENT_FOR_POST_REQUESTED',
  DELETE_COMMENT_FOR_POST_FAILED: 'DELETE_COMMENT_FOR_POST_FAILED',
  DELETE_COMMENT_FOR_POST_SUCCEEDED: 'DELETE_COMMENT_FOR_POST_SUCCEEDED',

  DELETE_COMMENT_REQUESTED: 'DELETE_COMMENT_REQUESTED',

  SEARCH_REQUESTED: 'SEARCH_REQUESTED',
  SEARCH_FAILED: 'SEARCH_FAILED',
  SEARCH_SUCCEEDED: 'SEARCH_SUCCEEDED',

  TAG_USER_REQUESTED: 'TAG_USER_REQUESTED',
  TAG_USER_FAILED: 'TAG_USER_FAILED',
  TAG_USER_SUCCEEDED: 'TAG_USER_SUCCEEDED',

  GET_REASONS_REQUESTED: 'GET_REASONS_REQUESTED',
  GET_REASONS_FAILED: 'GET_REASONS_FAILED',
  GET_REASONS_SUCCEEDED: 'GET_REASONS_SUCCEEDED',

  CREATE_POST_REQUESTED: 'CREATE_POST_REQUESTED',
  CREATE_POST_FAILED: 'CREATE_POST_FAILED',
  CREATE_POST_SUCCEEDED: 'CREATE_POST_SUCCEEDED',

  GET_LEADER_BOARD_REQUESTED: 'GET_LEADER_BOARD_REQUESTED',
  GET_LEADER_BOARD_FAILED: 'GET_LEADER_BOARD_FAILED',
  GET_LEADER_BOARD_SUCCEEDED: 'GET_LEADER_BOARD_SUCCEEDED',

  GET_NOTIFICATION_REQUESTED: 'GET_NOTIFICATION_REQUESTED',
  GET_NOTIFICATION_FAILED: 'GET_NOTIFICATION_FAILED',
  GET_NOTIFICATION_SUCCEEDED: 'GET_NOTIFICATION_SUCCEEDED',
};

export default CONSTANTS;
