import {
  loginCall,
  getPostsCall,
  changePasswordCall,
  getUserProfileCall,
  searchUsersCall,
  getReasonsCall,
  createPostCall,
  getLeaderBoardCall,
  getLikesForPostCall,
  getCommentsForPostCall,
  createCommentForPostCall,
  getUserDataCall,
  likeUnLikePostCall,
  forgotPasswordCall,
  updateUserDataCall,
  notificationCall,
  getPostCall,
  deleteCommentCall,
} from './calls';

export default {
  loginCall,
  getPostsCall,
  changePasswordCall,
  getUserProfileCall,
  searchUsersCall,
  getReasonsCall,
  createPostCall,
  getLeaderBoardCall,
  getLikesForPostCall,
  getCommentsForPostCall,
  createCommentForPostCall,
  getUserDataCall,
  likeUnLikePostCall,
  forgotPasswordCall,
  updateUserDataCall,
  notificationCall,
  getPostCall,
  deleteCommentCall,
};
